spring:
  datasource:
    username: postgres
    password: Grace@2002
    url: jdbc:postgresql://localhost:5432/geocoding
  jpa:
    hibernate:
      ddl-auto: update
storeApi: store
companyApi: company
distanceApi: findDistance
