spring:
  datasource:
    username: postgres
    password: Grace@2002
    url: jdbc:postgresql://localhost:5432/geocoding
  data:
    mongodb:
      database: geocoding
      port: 27017
      host: localhost
      uri: mongodb://localhost:27017/geocoding
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:file:.env[.properties]
#  security:
#    user:
#      name: user
#      password: hai
storeApi: store
companyApi: company
distanceApi: findStores
planApi: plan
subscriptionApi: subscribe
companyLoginApi: companyLogin
apiKey: generateApikey
#noCompanyException: no such company present

privateKey: ${privatekey}
