spring:
  datasource:
    username: postgres
    password: Grace@2002
    url: jdbc:postgresql://localhost:5432/geocoding
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  security:
#    user:
#      name: user
#      password: hai
storeApi: store
companyApi: company
distanceApi: findDistance
planApi: plan
subscriptionApi: subscribe
#noCompanyException: no such company present
