spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/Bill
    username: postgres
    password: Grace@2002
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: gracelinjonax247@gmail.com
    password: kodo qaqr dsde hrgf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG