spring:
  name: tenant-1
  datasource:
      url: jdbc:sqlserver://127.0.0.1:1433;databaseName=cart;encrypt=true;trustServerCertificate=true
      username: sa
      password: sa
  jpa:
    hibernate:
      ddl-auto: update
#spring:
#  config:
#    activate:
#      on-profile: tenant-2
#  name: tenant-2
#  datasource:
#    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=cart2;encrypt=true;trustServerCertificate=true
#    username: sa
#    password: sa
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
server:
  port: 8081
#keycloak:
#  restart: always
#  environment:
#    - KEYCLOAK_ADMIN=admin
#    - KEYCLOAK_ADMIN_PASSWORD=password
#  ports:
#    - "8081:8080"
#  command:
#    - start-dev
keycloak:
  clientId: solutionspace-app
  clientSecret: e3701156-07b2-43b3-88e3-ddc65dbc9b5c
  authurl: https://localhost:8081
#  authurl: https://dev-aaa.boschindia-mobilitysolutions.com/auth/realms/Rlm_ROBOIN_SolutionSpace_IN/protocol/openid-connect/token
#accesskey-module-keyvalue: pjmsaccesssecretkey
#accesskey-module-saltvalue: pjmsaccesssecretsalt
#logging.level.com.zaxxer.hikari=DEBUG
tenants:
  default: mkos
  datasources:
    mkos:
      jdbcUrl: jdbc:sqlserver://127.0.0.1:1433;databaseName=cart;encrypt=true;trustServerCertificate=true
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: sa