spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=Bill;encrypt=true;trustServerCertificate=true
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: gracelinjonax247@gmail.com
    password: kodo qaqr dsde hrgf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
