spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingService
    username: postgres
    password: Grace@2002
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      database: bookingService
      port: 27017
      host: localhost
      uri: mongodb://localhost:27017/bookingService
